spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nagomin?serverTimezone=Asia/Seoul
    username: root
    password: tnwls5722!
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
 # show_sql: true
        format_sql: true
        
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      location: upload
        
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security.web: trace
 
value:
  encryptor:
    key : gkI9QE2yo147b70 
  jwt:
    key : VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa